"""empty message

Revision ID: 4359ed34fd01
Revises: a862494982d1
Create Date: 2019-08-31 09:06:16.163954

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4359ed34fd01'
down_revision = 'a862494982d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'created_date')
    # ### end Alembic commands ###
